---
title: Zen Browser Installation
description: Installs Zen Browser
actions:
  - !run:
      runas: currentUserElevated
      exeDir: true
      wait: true
      exe: "powershell"
      args: '-EP Bypass -C ".\\Scripts\\Setup\\SOFTWARE.PS1 -Software Install-Zen"'
