---
title: Explorer Menu
description: Applies Explorer menu and desktop tweaks via EXPLORER.PS1
privilege: TrustedInstaller
actions:
  - !cmd: {command: 'net user defaultuser0 >nul 2>&1 && net user defaultuser0 /delete >nul 2>&1 & exit 0', onUpgrade: false}
  - !powerShell: {command: '.\\Scripts\\EXPLORER.PS1', exeDir: true, runas: currentUserElevated, wait: true}
  - !registryKey: {path: 'HKCR\*\shell\pintohomefile'}
  - !registryKey: {path: 'HKCR\Folder\shell\pintohome'}
