---
title: Explorer
description: Applies Explorer tweaks
privilege: TrustedInstaller
actions:

  - !status: {status: 'Fixing Explorer Bags'}
  - !run:
      exeDir: true
      exe: 'powershell.exe'
      args: '-NoProfile -ExecutionPolicy Bypass -File ".\Scripts\EXPLORER_DOWNLOADS_BAGS_FIX.PS1"'
      wait: true
      weight: 100

  - !status: {status: 'Fixing Folder Types'}
  - !run:
      exeDir: true
      exe: 'powershell.exe'
      args: '-NoProfile -ExecutionPolicy Bypass -File ".\Scripts\EXPLORER_FOLDER_TYPES_FIX.PS1"'
      wait: true
      weight: 100

  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\ImmersiveShell', value: 'ConvertibleSlateModePromptPreference', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\ImmersiveShell', value: 'SignInMode', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'ShowCopilotButton', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKCU\Software\Policies\Microsoft\Windows\WindowsCopilot', value: 'TurnOffWindowsCopilot', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsCopilot', value: 'TurnOffWindowsCopilot', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer', value: 'HideSCAMeetNow', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer', value: 'HideSCAMeetNow', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'TaskbarSn', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'ShowInfoTip', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'ShowPreviewHandlers', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'ShowStatusBar', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'GroupByType', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'LaunchGallery', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKCU\Software\Classes\CLSID\{e88865ea-0e1c-4e20-9aa6-edcd0212c87c}', value: 'System.IsPinnedToNameSpaceTree', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKCU\Software\Classes\CLSID\{F02C1A0D-BE21-4350-88B0-7367FC96EF3C}', value: 'System.IsPinnedToNameSpaceTree', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\NonEnum', value: '{F02C1A0D-BE21-4350-88B0-7367FC96EF3C}', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer', value: 'HubMode', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'LaunchTo', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKU\.DEFAULT\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'LaunchTo', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Dsh', value: 'IsPrelaunchEnabled', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer', value: "link", type: REG_BINARY, data: "00000000"}
  - !registryValue: {path: 'HKU\.DEFAULT\Software\Microsoft\Windows\CurrentVersion\Explorer', value: "link", type: REG_BINARY, data: "00000000"}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer', value: "MultipleInvokePromptMinimum", type: REG_DWORD, data: '200'}
  - !registryValue: {path: 'HKU\.DEFAULT\Software\Microsoft\Windows\CurrentVersion\Explorer', value: "MultipleInvokePromptMinimum", type: REG_DWORD, data: '200'}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer', value: "LinkResolveIgnoreLinkInfo", type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKU\.DEFAULT\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer', value: "LinkResolveIgnoreLinkInfo", type: REG_DWORD, data: '1' }
  - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Start', value: "ShowAllAppsSection", type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Start', value: "StartMenuSize", type: REG_DWORD, data: '1'}
