---
title: Add Theme
description: Adds and sets the LexBoosT themes by default
option: "configure-theme"
privilege: Admin
actions:

  - !powerShell: {
      command: '.\\Scripts\\UI\\THEME_DEPLOY.PS1 -Action InstallTheme',
      exeDir: true,
      runas: currentUserElevated,
      wait: true,
    }

    # Set LexBoosT theme as default for new users
  - !registryValue: {
      path: 'HKCU\Software\Policies\Microsoft\Windows\Personalization',
      value: "ThemeFile",
      type: REG_SZ,
      data: "%windir%\\Resources\\Themes\\LexBoosT-v3.0-dark.theme",
    }
  - !status: {
      status: "Modify User Folder icon",
    }
  - !run:
    exeDir: true
    exe: ".\\Scripts\\UI\\FOLDER_USER.CMD"
    runas: currentUserElevated
    wait: true

  - !status: {
      status: "Watch out for your eyes!",
    }
  - !run:
    exeDir: true
    exe: ".\\Scripts\\PAUSE.CMD"
    runas: currentUserElevated
    wait: true
    weight: 300

  - !status: {
      status: "Success!",
    }
  - !run:
    exe: "explorer.exe"
    exeDir: false
    runas: currentUser
    wait: false

  - !status: {
      status: "Thanks to try my OS",
    }
  - !run:
    exeDir: true
    exe: ".\\Scripts\\PAUSE.CMD"
    runas: currentUserElevated
    wait: true
    weight: 200
