---
title: Mouse
description: Applies mouse/pointer tweaks via MOUSE.PS1
privilege: TrustedInstaller
actions:
  - !status: {status: 'Applying Mouse Tweaks'}
  - !powerShell: {command: '.\\Scripts\\MOUSE.PS1', exeDir: true, runas: currentUserElevated, wait: true}
