---
title: Zen Browser Installation
description: Installs Zen Browser
privilege: TrustedInstaller
actions:
  - !run:
      runas: currentUserElevated
      exeDir: true
      wait: true
      option: "Zen"
      exe: "powershell"
      args: '-EP Bypass -C ".\\Scripts\\SOFTWARE.PS1 -Software Install-Zen"'
