---
title: Configure boot
description: Configure boot settings
privilege: TrustedInstaller
actions:

  - !registryValue: {
      path: 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System',
      value: "DelayedDesktopSwitchTimeout",
      operation: delete,
    }
  # Optimiser prefetch boot
  - !registryValue: {
      path: 'HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\PrefetchParameters',
      value: "BootId",
      type: REG_DWORD,
      data: "1",
    }