---
title: Vulnerable Driver Blocklist
description: Enables Microsoft's vulnerable driver blocklist
privilege: TrustedInstaller
actions:
  - !status: {
      status: 'Enabling vulnerable driver blocklist',
    }
  - !registryValue: {
      path: 'HKLM\SYSTEM\CurrentControlSet\Control\CI\Config',
      value: "VulnerableDriverBlocklistEnable",
      type: REG_DWORD,
      data: "0",
    }