---
title: Configure Control Panel
description: Configure Control Panel
privilege: TrustedInstaller
actions:
  # === ActiveWndTrkTimeout — Délai avant activation d'une fenêtre au survol (10ms)
  - !registryValue: {
      path: 'HKCU\Control Panel\Desktop',
      value: "ActiveWndTrkTimeout",
      type: REG_DWORD,
      data: "10",
    }
  - !registryValue: {
      path: 'HKU\.DEFAULT\Control Panel\Desktop',
      value: "ActiveWndTrkTimeout",
      type: REG_DWORD,
      data: "10",
    }

  # === Disables the blue screen that pops up when you're trying to shutdown or restart, asking you to save your work.
  - !registryValue: {
      path: 'HKCU\Control Panel\Desktop',
      value: "AutoEndTasks",
      type: REG_SZ,
      data: "1",
    }
  - !registryValue: {
      path: 'HKU\.DEFAULT\Control Panel\Desktop',
      value: "AutoEndTasks",
      type: REG_SZ,
      data: "1",
    }

  # === HungAppTimeout also specifies how long (5 seconds by default) the system waits for user processes to end after the user clicks/taps on the End task button in Task Manager.
  - !registryValue: {
      path: 'HKCU\Control Panel\Desktop',
      value: "HungAppTimeout",
      type: REG_SZ,
      data: "1000",
    }
  - !registryValue: {
      path: 'HKU\.DEFAULT\Control Panel\Desktop',
      value: "HungAppTimeout",
      type: REG_SZ,
      data: "1000",
    }

  # === The WaitToKillAppTimeout value determines how long the system waits for user processes to end after the user attempts to sign out, restart, or shut down Windows.
  - !registryValue: {
      path: 'HKCU\Control Panel\Desktop',
      value: "WaitToKillAppTimeout",
      type: REG_SZ,
      data: "1000",
    }
  - !registryValue: {
      path: 'HKU\.DEFAULT\Control Panel\Desktop',
      value: "WaitToKillAppTimeout",
      type: REG_SZ,
      data: "1000",
    }

  # === This value controls the timeout period in milliseconds for all low-level hooks.
  - !registryValue: {
      path: 'HKCU\Control Panel\Desktop',
      value: "LowLevelHooksTimeout",
      type: REG_SZ,
      data: "1000",
    }
  - !registryValue: {
      path: 'HKU\.DEFAULT\Control Panel\Desktop',
      value: "LowLevelHooksTimeout",
      type: REG_SZ,
      data: "1000",
    }
  - !registryValue: {
      path: 'HKU\.DEFAULT\Control Panel\Desktop',
      value: "SmoothScroll",
      type: REG_SZ,
      data: "0",
    }

  # === Removes Ease of Access -> MouseKeys features tied to alteration of Sensitivity
  - !registryValue: {
      path: 'HKCU\Control Panel\Accessibility\MouseKeys',
      value: "MaximumSpeed",
      operation: delete,
    }
  - !registryValue: {
      path: 'HKCU\Control Panel\Accessibility\MouseKeys',
      value: "TimeToMaximumSpeed",
      operation: delete,
    }
  # DEFAULT USER
  - !registryValue: {
      path: 'HKU\.DEFAULT\Control Panel\Accessibility\MouseKeys',
      value: "MaximumSpeed",
      operation: delete,
    }
  - !registryValue: {
      path: 'HKU\.DEFAULT\Control Panel\Accessibility\MouseKeys',
      value: "TimeToMaximumSpeed",
      operation: delete,
    }

  # === Allow Online Tips
  # ------> If disabled, Settings will not contact Microsoft content services to retrieve tips and help content.
  - !registryValue: {
      path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer',
      value: "AllowOnlineTips",
      type: REG_DWORD,
      data: "0",
    }

  # ===================================================
  # === Disable Ease of Access features in Registry ===
  # ===================================================
  # === Disable Ease of Access features (HKEY_CURRENT_USER)
  - !registryValue: {
      path: 'HKCU\Control Panel\Accessibility\AudioDescription',
      value: "Flags",
      type: REG_SZ,
      data: "0",
    }
  - !registryValue: {
      path: 'HKCU\Control Panel\Accessibility\Blind Access',
      value: "Flags",
      type: REG_SZ,
      data: "0",
    }
  - !registryValue: {
      path: 'HKCU\Control Panel\Accessibility\HighContrast',
      value: "Flags",
      type: REG_SZ,
      data: "0",
    }
  - !registryValue: {
      path: 'HKCU\Control Panel\Accessibility\Keyboard Preference',
      value: "Flags",
      type: REG_SZ,
      data: "0",
    }
  - !registryValue: {
      path: 'HKCU\Control Panel\Accessibility\MouseKeys',
      value: "Flags",
      type: REG_SZ,
      data: "0",
    }
  - !registryValue: {
      path: 'HKCU\Control Panel\Accessibility\On',
      value: "Flags",
      type: REG_SZ,
      data: "0",
    }
  - !registryValue: {
      path: 'HKCU\Control Panel\Accessibility\ShowSounds',
      value: "Flags",
      type: REG_SZ,
      data: "0",
    }
  - !registryValue: {
      path: 'HKCU\Control Panel\Accessibility\SlateLaunch',
      value: "Flags",
      type: REG_SZ,
      data: "0",
    }
  - !registryValue: {
      path: 'HKCU\Control Panel\Accessibility\SoundSentry',
      value: "Flags",
      type: REG_SZ,
      data: "0",
    }
  # DEFAULT USER
  - !registryValue: {
      path: 'HKU\.DEFAULT\Control Panel\Accessibility\AudioDescription',
      value: "Flags",
      type: REG_SZ,
      data: "0",
    }
  - !registryValue: {
      path: 'HKU\.DEFAULT\Control Panel\Accessibility\Blind Access',
      value: "Flags",
      type: REG_SZ,
      data: "0",
    }
  - !registryValue: {
      path: 'HKU\.DEFAULT\Control Panel\Accessibility\HighContrast',
      value: "Flags",
      type: REG_SZ,
      data: "0",
    }
  - !registryValue: {
      path: 'HKU\.DEFAULT\Control Panel\Accessibility\Keyboard Preference',
      value: "Flags",
      type: REG_SZ,
      data: "0",
    }
  - !registryValue: {
      path: 'HKU\.DEFAULT\Control Panel\Accessibility\Keyboard Response',
      value: "Flags",
      type: REG_SZ,
      data: "122",
    }
  - !registryValue: {
      path: 'HKU\.DEFAULT\Control Panel\Accessibility\MouseKeys',
      value: "Flags",
      type: REG_SZ,
      data: "0",
    }
  - !registryValue: {
      path: 'HKU\.DEFAULT\Control Panel\Accessibility\On',
      value: "Flags",
      type: REG_SZ,
      data: "0",
    }
  - !registryValue: {
      path: 'HKU\.DEFAULT\Control Panel\Accessibility\ShowSounds',
      value: "Flags",
      type: REG_SZ,
      data: "0",
    }
  - !registryValue: {
      path: 'HKU\.DEFAULT\Control Panel\Accessibility\SlateLaunch',
      value: "Flags",
      type: REG_SZ,
      data: "0",
    }
  - !registryValue: {
      path: 'HKU\.DEFAULT\Control Panel\Accessibility\SoundSentry',
      value: "Flags",
      type: REG_SZ,
      data: "0",
    }

  # === Disable Online Tips via PolicyManager
  - !registryValue: {
      path: 'HKLM\SOFTWARE\Microsoft\PolicyManager\default\Settings\AllowOnlineTips',
      value: "value",
      type: REG_DWORD,
      data: "0",
    }
  # === Disable Online Tips via System Policies
  - !registryValue: {
      path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\System',
      value: "AllowOnlineTips",
      type: REG_DWORD,
      data: "0",
    }
  # === Hide Disconnected Audio Devices
  - !registryValue: {
      path: 'HKCU\SOFTWARE\Microsoft\Multimedia\Audio\DeviceCpl',
      value: "ShowDisconnectedDevices",
      type: REG_DWORD,
      data: "0",
    }
  # === Hide Hidden Audio Devices
  - !registryValue: {
      path: 'HKCU\SOFTWARE\Microsoft\Multimedia\Audio\DeviceCpl',
      value: "ShowHiddenDevices",
      type: REG_DWORD,
      data: "0",
    }