---
title: Remove Win32 apps
description: Removal of Win32 apps
privilege: TrustedInstaller
actions:
  # Disable Smart App Control
  # Causes slow app loading issues and sends data to Microsoft
  - !registryValue: {
    path: 'HKLM\SYSTEM\CurrentControlSet\Control\CI\Policy',
    value: "VerifiedAndReputablePolicyState",
    data: "0",
    type: REG_DWORD,
    }
  - !registryValue: {
      path: 'HKLM\SYSTEM\CurrentControlSet\Control\CI\Policy',
      value: "WHQLSettings",
      type: REG_DWORD,
      data: "1",
    }

  # Microsoft Edge
  - !status: {
      status: "Removing MS Edge",
      option: "remove-edge",
    }
  - !taskKill: {
      name: "MicrosoftEdgeUpdate",
      errorAction: Ignore,
      option: "remove-edge",
    }
  - !taskKill: {
      name: "msedge",
      errorAction: Ignore,
      option: "remove-edge",
    }
  - !taskKill: {
      name: "MicrosoftEdge*",
      errorAction: Ignore,
      option: "remove-edge",
    }
  - !taskKill: {
      name: "setup",
      errorAction: Ignore,
      pathContains: "\\Edge",
      option: "remove-edge",
    }

  - !powerShell:
    command: '.\\Scripts\\Cleanup\\EDGE.PS1 -Mode EdgeBrowser'
    exeDir: true
    runas: currentUserElevated
    option: "remove-edge"
    weight: 40

  - !powerShell:
    option: "remove-edge"
    wait: true
    exeDir: true
    errorAction: Ignore
    weight: 30
    command: >-
      .\\Scripts\\Cleanup\\APPX-REMOVER.PS1 -Packages @(
        'Microsoft.MicrosoftEdge',
        'Microsoft.MicrosoftEdgeDevToolsClient'
        'Microsoft.Edge.GameAssist'
      ) -Force
    runas: currentUserElevated

  # OneDrive
  - !status: {
      status: "Removing OneDrive",
      option: "remove-onedrive",
    }
  - !taskKill: {
      name: "OneDriveStandaloneUpdater",
      errorAction: Ignore,
      option: "remove-onedrive",
    }
  - !taskKill: {
      name: "OneDriveSetup",
      errorAction: Ignore,
      option: "remove-onedrive",
    }
  - !taskKill: {
      name: "OneDrive*",
      errorAction: Ignore,
      option: "remove-onedrive",
    }
  - !taskKill: {
      name: "FileCoAuth",
      errorAction: Ignore,
      option: "remove-onedrive",
    }
  - !taskKill: {
      name: "Microsoft.SharePoint*",
      errorAction: Ignore,
      option: "remove-onedrive",
    }
  - !service: {
      name: "OneSyncSvc*",
      operation: delete,
    }
  - !run: {
      exeDir: true,
      exe: ".\\Scripts\\Cleanup\\ONED.CMD",
      option: "remove-onedrive",
      weight: 40,
    }
  - !file: {
      path: "%SystemDrive%\\OneDriveTemp",
      option: "remove-onedrive",
    }
  - !file: {
      path: "%ProgramData%\\Microsoft OneDrive",
      option: "remove-onedrive",
    }

  - !powerShell:
    option: "remove-onedrive"
    wait: true
    exeDir: true
    errorAction: Ignore
    weight: 10
    command: >-
      .\\Scripts\\Cleanup\\APPX-REMOVER.PS1 -Packages @(
        'OneDrive*',
        'microsoft.microsoftskydrive'
      ) -Force
    runas: currentUserElevated
